server:
  port: 8082

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb+srv://kavi:ImluNYDuYoeXJy5G@cluster0.ncaaifi.mongodb.net/ceylonica_user?retryWrites=true&w=majority

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
