# Server
server.port=8086

# Application
spring.application.name=payment-service

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/ceylonica

# Stripe
stripe.secret-key=
stripe.publishable-key=

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true