server.port=8083

spring.application.name=product-service

spring.data.mongodb.uri=mongodb://localhost:27017/ceylonica
spring.data.mongodb.database=ceylonica

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.instance.prefer-ip-address=true

# File Upload Limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
