spring.application.name=cart-service
server.port=8085

# 1. Updated with your new password: PNoQLcGsg0wVMp8u
spring.data.mongodb.uri=mongodb+srv://kavindyasamara:<db_password>@cluster1.mjrkouw.mongodb.net/?appName=Cluster1
spring.data.mongodb.database=cart