server:
  port: 8084

spring:
  application:
    name: cart-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/ceylonica_cart

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
